### ISSUE TITLE
Titles not reflecting current entry

### ISSUE THREAD

**Issue by davidatkinswwt** [aerni/statamic-advanced-seo#1]
When viewing <head> or sharing, the og:title and twitter:title do not reflect the current entry's title.

Everything else is correct: image, url, content, etc.

This also happens with other collections on the same site.

I have cleared caches, tried different browsers, and machines.

Looking for any suggestions...

**Comment by aerni** [comment]
I can't reproduce this issue. Everything works fine for me. Can you share more about your setup, versions, and what you've tried? Also, is this a multi-site?

**Comment by davidatkinswwt** [comment]
Alright so I poked around some more and think I've found the issue. 

In my show.antlers.html file I am rendering another set of collections:

`
{{ collection:events }}
  {{ title }} {{ description }}
{{  /collection:events }}
`

When I comment this section out the title works fine. Add it back in and I'm back to my issue above. I tried in another collection with a similar setup. Commenting out the section solves the issue.

**Comment by aerni** [comment]
Can you please be more specific? Are you talking about a setup like the following? If yes, I still can't reproduce the issue. I get the correct title on whatever view I'm on.

```html
<div>
    The page title: {{ title }}
</div>

<div>
    {{ collection:events }}
        <div>
            The events title: {{ title }}
        </div>
    {{ /collection:events }}
</div>
```

**Comment by davidatkinswwt** [comment]
Yes. 

My folder structure is:
events/
  - index.antlers.html
  - show.antlers.html
  
`
// show.antlers.html
<div>
    Page Title:  {{ title }}
</div>

<div>
     {{ collection:events :id:not="id" limit="3" sort="date:desc" paginate="true" as="items" }}
          <div>
               {{ items }}
                   <div>
                         Event: {{ title }}
                   </div>
               {{ /items }}
          </div>
</div>
`

**Comment by aerni** [comment]
I still can't reproduce this. Please whip up a fresh site that reproduces the issue and share the repo with me.

**Comment by davidatkinswwt** [comment]
https://github.com/davidatkinswwt/testsite-advanced-seo

**Comment by aerni** [comment]
Thank you, this helped a lot! Was able to fix it in a matter of minutes.
