### ISSUE TITLE
seoMeta query: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by maartenvanhunsel** [aerni/statamic-advanced-seo#107]
When upgrading to Statamic version 4.32.0 our query for fetching seo related data fails. Statamic returns immediate the following error:`Maximum execution time of 30 seconds exceeded`

Query is as simple as:
```
query MyQuery {
  seoMeta(id: "home") {
    computed {
      title
    }
  }
}
```

However I won't see any direct relation within this update.

**Comment by aerni** [comment]
I just tested this on a fresh installation and can't reproduce the error. Must be something unique to your site and likely unrelated to Advanced SEO. Please try to reproduce this issue in a repo and send it over, so I can take a look at it.

**Comment by aerni** [comment]
Did you resolve this issue?
