### ISSUE TITLE
SEO generate images saving on local

### ISSUE THREAD

**Issue by owuraku** [aerni/statamic-advanced-seo#109]
I have changed the config to generate and save SEO images into a cloud container however when I run `php artisan SEO:generate-images`, it creates a new folder in the local disk and save the images there, however, the metadata is sent to the cloud container.

**Comment by aerni** [comment]
Can you share the configuration of your asset container and filesystem disk?

**Comment by aerni** [comment]
Is this still an issue? Or did you get this solved?
