### ISSUE TITLE
Not possible to translate SEO title for custom routes

### ISSUE THREAD

**Issue by Web10-Joris** [aerni/statamic-advanced-seo#111]
I've tried to translate the seo title and description for a custom route but without success. This is the route.php:
```        
Route::statamic('/custom', 'custom.index', [
            'seo_enabled' => true,
            'seo_title' => __('seo.cart_title'),
            'seo_description' => __('seo.cart_description')]);
```

And the HTML for this route is outputting:
`<title> seo.cart_title | SiteName </title>`

The correct lang folder and file are set up with translations for the current user locale. 

Is this something that I can fix myself or does it need to be inside the addon?

**Comment by aerni** [comment]
I fiddled around with your site a little. The issue is related to the setup of your routes. You have to figure that one out. The issue isn't related to Advanced SEO.

**Comment by aerni** [comment]
Yeah, so this is probably a Statamic bug. Most likely related to the [Localize Middleware](https://github.com/statamic/cms/blob/4.x/src/Http/Middleware/Localize.php). Best to open an issue there.

You can work around it by using a regular Laravel route, that returns a Statamic view and setting the app locale to the locale of the current site.

```php
Site::all()->each(function ($site) {
    Route::get("{$site->url()}/test", function () use ($site) {
        App::setLocale($site->shortLocale());

        return View::make('layout', [
            'seo_enabled' => true,
            'seo_title' => __('seo.title'),
        ]);
    });
});
```
