### ISSUE TITLE
Google Search Console - JSON-LD Breadcrumbs - Invalid object type for field "itemListElement"

### ISSUE THREAD

**Issue by markguleno** [aerni/statamic-advanced-seo#12]
## Summary
After adding my production website to the [Google Search Console](https://search.google.com/search-console/welcome), I get the following error on pages (other than the home page):

    Invalid object type for field "itemListElement"

The primary cause is that the "itemListElement" value array is wrapped in double quotes and the each item in the array has its double quotes escaped.

I verified this as follows:
1. Test the broken version
    a. View the source of one of the broken pages
    b. Copy the contents of the <script type="application/ld+json"> tag into the [Google Rich Results Test](https://search.google.com/test/rich-results) "CODE" tab, replacing the existing <script> tag content
    c. Click the "RUN TEST" button 
    d. The test fails with an ***"Invalid object type for field "itemListElement"*** error
2. Create and test a fixed version
    a. View the source of one of the broken pages
    b. Copy the contents of the <script type="application/ld+json"> tag into a text editor
    c. Remove the double quotes around the "itemListElement" value array
    d. Search and replace the escaped quotes by replacing \" with "
    e. Search and replace the escaped slashes by replacing \\\/ with / & \/ with /
    f. Copy and paste this fixed version into the [Google Rich Results Test](https://search.google.com/test/rich-results) "CODE" tab, replacing the existing <script> tag content
    g. Click the "RUN TEST" button 
    h. The test passes

## Additional comments
1. The "id" attribute should be named "@id" as per [Schema.org itemListElement](https://schema.org/itemListElement)
2. The "itemListElement" value array doesn't need a "@context" attribute
3. Unlike [Schema.org's example](https://schema.org/itemListElement) where the "name" attribute is a child of "item", (Google's breadcrumb example)[https://developers.google.com/search/docs/advanced/structured-data/breadcrumb] simply puts the "name" attribute at the same level as "item" and set's the "item" attribute's value to the url
4. The slashes don't need to be escaped

## Expected behavior
Looking at examples in [Google's Advanced SEO Breadcrumb documentation](https://developers.google.com/search/docs/advanced/structured-data/breadcrumb), I see the following:
1. The "itemListElement" value array isn't enclosed in quotes
2. The "itemListElement" value array elements attribute names and string values are quoted, but they don't have their double quotes escaped because of point number 1 above
3. The "@context" attribute is only used at the root level of the JSON+LD tree

Looking at Schema.org definition of [itemListElement](https://schema.org/itemListElement) "JSON-LD" tab, the "id" attribute should be named "@id"

Neither of those examples uses ***"@type": "Thing"***

Therefore, the generated breadcrumb should look like either one of the following:

### Schema.org itemListElement format
```html
<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [{
            "@type": "ListItem",
            "position": 1,
            "item": {
                "id": "http://www.domain.com",
                "name": "Home"
            }
        },{
            "@type": "ListItem",
            "position": 2,
            "item": {
                "id": "http://www.domain/page",
                "name": "Page"
            }
        }]
    }
</script>
```

### Google breadcrumb format
```html
<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [{
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": "http://www.domain.com"
        },{
            "@type": "ListItem",
            "position": 2,
            "name": "Page",
            "item": "http://www.domain/page"
        }]
    }
</script>
```

## Actual behavior
Viewing the page source of one of the broken pages, I see the following:

### Advanced SEO v1.1.3 breadcrumb format
```html
<script type="application/ld+json">
    {
        "@context":"https:\/\/schema.org",
        "@type":"BreadcrumbList",
        "itemListElement": "[{
            \"@context\":\"https:\\\/\\\/schema.org\",
            \"@type\":\"ListItem\",
            \"position\":1,
            \"item\": {
                \"@type\":\"Thing\",
                \"id\":\"http:\\\/\\\/www.domain.com\",
                \"name\":\"Home\"
            }
        },{
            \"@context\":\"https:\\\/\\\/schema.org\",
            \"@type\":\"ListItem\",
            \"position\":2,
            \"item\": {
                \"@type\":\"Thing\",
                \"id\":\"http:\\\/\\\/www.domain\\\/page\",
                \"name\":\"Page\"
            }
        }]"
    }
</script>
```

## Versions used
* Statamic v3.3.13
* Advanced SEO v1.1.3

**Comment by aerni** [comment]
Thanks. Will look into this.

**Comment by aerni** [comment]
I just released a fix for this. The breadcrumbs now pass the test. The escaping of the URLs wasn't an issue after all. This addon uses [Spatie's battle-tested schema package](https://github.com/spatie/schema-org) under the hood. The structural issue happened because of a mistake on my side of things.

**Comment by markguleno** [comment]
Michael, thank you for fixing the issue.  Unfortunately, the fix caused a new issue #14.

**Comment by aerni** [comment]
Ha, gotcha. Will fix it asap.

**Comment by markguleno** [comment]
I can confirm that the breadcrumbs on all pages that previously showed the error on v1.1.3 now validate correctly using v1.1.5 according to [Google's Rich Results Test](https://search.google.com/test/rich-results).
