### ISSUE TITLE
hreflang with only country?

### ISSUE THREAD

**Issue by JorisOrangeStudio** [aerni/statamic-advanced-seo#132]
Hi,
Is it possible to have the hreflang rendered only with the country code? 
Now the output is like this: 
```
<link rel="alternate" href="http://localhost" hreflang="nl-NL">
<link rel="alternate" href="http://localhost/en" hreflang="en-US">
```

But we want this to be (to include also other countries with the same languages): 
```
<link rel="alternate" href="http://localhost" hreflang="nl">
<link rel="alternate" href="http://localhost/en" hreflang="en">
```

And the possibility to add the **x-default** hreflang
`<link rel="alternate" href="http://localhost" hreflang="x-default" />`

**Comment by aerni** [comment]
The `hreflang` will be the whatever you define as the locale in your `sites.php`. So you can just change it there from `nl_NL` to `nl` and `en_US` to `en`.

If you can't do that, you can always publish the Advanced SEO views and modify the `hreflang` there using Antlers.

Adding `x-default` is on my list of features.

**Comment by aerni** [comment]
Just letting you know that support for `x-default` has been added in https://github.com/aerni/statamic-advanced-seo/pull/156.
