### ISSUE TITLE
Support for Statamic 5 and Laravel 11

### ISSUE THREAD

**Issue by voicecode-bv** [aerni/statamic-advanced-seo#134]
Hi there, 

Can you please add support for Laravel 11?

Thanks!

**Comment by aerni** [comment]
Statamic is not yet compatible with Laravel 11. I'll add support as soon as Statamic 5 is released.

**Comment by voicecode-bv** [comment]
Ah sorry, that makes sense. Thank you!

**Comment by JoeriE** [comment]
It would be great to have compatibility with Laravel 11, since Statamic 5 is almost being released!

**Comment by aerni** [comment]
I will tackle the upgrade whenever Statamic 5 is released and the upgrade path is clear.

**Comment by maartenvanhunsel** [comment]
As you may noticed, Statamic 5 is out 🥳

**Comment by aerni** [comment]
Yes! 🎉 It will take some time to make this addon compatible. No ETA at this point. But I'm on it. I have many projects myself that rely on this update.
