### ISSUE TITLE
BadMethodCallException - Call to undefined method Statamic\Entries\Entry::title()

### ISSUE THREAD

**Issue by markguleno** [aerni/statamic-advanced-seo#14]
## Summary
After upgrading to Advanced SEO v1.1.4, visiting a page in a collection (https://www.domain.com/collection/page) results in a ***BadMethodCallException - Call to undefined method Statamic\Entries\Entry::title()*** error:

![title-error](https://user-images.githubusercontent.com/46555125/171905204-f52ebeac-3947-40e4-ac8d-16fb92b16a44.png)

## Workaround

Either rolling back to Advanced SEO v1.1.3 or commenting out the ***{{ seo:head }}*** tag in layout.antlers.html allows the page to load properly.

## Versions used
* Statamic v3.3.13
* Advanced SEO v1.1.4
* PHP 8.1.6
* Laravel 9.5.1

**Comment by aerni** [comment]
Hmm, I can't seem to reproduce this. What kind of page are you on? Entry, Taxonomy?

**Comment by markguleno** [comment]
The error occurs on all entry pages in an "Articles" collection.  So, the url is https://www.domain.com/articles/page.  The error doesn't occur on entries in the default "Pages" collection.

**Comment by aerni** [comment]
I hunted it down. The issue only happens when the collection isn't structured. I'll get a fix out soon.

**Comment by markguleno** [comment]
Thank you for hunting down and fixing the issue.  I can confirm that the error is gone using v1.1.5.
