### ISSUE TITLE
CI pipeline broken, because package tries to get value from cache

### ISSUE THREAD

**Issue by goellner** [aerni/statamic-advanced-seo#150]
have a CI pipelline on github set up, which fails now. this is the error: 

```
Database file at path [/home/runner/work/asdf-website/asdf-website/apps/cms/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: select * from "cache" where "key" = laravel_cache_marketplace-packages/aerni/advanced-seo/v2.5.3 limit 1)
````

I have no database for running this action (php-cs-fixer) and shouldn't need one.

**Comment by aerni** [comment]
Hmm, no idea what to do with this error. Advanced SEO doesn't require any type of database, and I've never run into this. The error is most likely related to your specific setup.

**Comment by aerni** [comment]
Were you able to solve this issue?
