### ISSUE TITLE
Labels no more translated

### ISSUE THREAD

**Issue by GuyVervillePerso** [aerni/statamic-advanced-seo#151]
Hello,

I have the latest version of your add-on, but suddenly, I lost all translations. Do you have any idea?
![CleanShot 2024-06-21 at 10 28 58@2x](https://github.com/aerni/statamic-advanced-seo/assets/69694028/b87716c8-fab2-4f14-b73b-3ead9d24dddd)

**Comment by aerni** [comment]
What version of Statamic are you on? This was a bug that had been fixed before. It might be a regression. See https://github.com/aerni/statamic-advanced-seo/issues/20 for a workaround.

**Comment by GuyVervillePerso** [comment]
I have the latest version of Statamic. It worked. The default locale is French, not English. Thanks.
