### ISSUE TITLE
Variables in taxonomy routes  are not parsed

### ISSUE THREAD

**Issue by pmeissner** [aerni/statamic-advanced-seo#159]
After updating to Statamic 5, the routes for my taxonomies don't render the variables. In my routes web.php file I have:
```
Route::statamic('covers/tags/{term}', 'work/tags/show', [
'seo_enabled' => true,
'seo_title' => '{{ term | title }} Covers',
'seo_description' => 'Amazing book covers designed by theBookDesigners.',
]);
```
The template gets rendered:
```
<title>{{ term | title }} Covers > theBookDesigners</title>
```

I think it was working previous to the CMS upgrade.

**Comment by aerni** [comment]
Thanks for raising this issue. There was a big refactor on Statamic's end concerning the augmentation process. Once PR https://github.com/statamic/cms/pull/10414 is merged, I'll be able to fix this issue.
