### ISSUE TITLE
Incomplete SEO metadata in head

### ISSUE THREAD

**Issue by ikmolbo** [aerni/statamic-advanced-seo#169]
Hi,

I have just installed Advanced SEO into a new Statamic site. So far, I have set a default (site wide) site name, and also some defaults for my Pages collection.

I have added the `{{ seo:meta }}` tag to the head section of my Antlers layout.

However, the only output I see in the head section from this tag, when viewing an entry from the Pages collection, is `<meta property="og:type" content="website”>`.

Here is the output of `seo:dump`:

![SCR-20241004-penn](https://github.com/user-attachments/assets/2fcf37bf-664b-4226-b7fb-1bf015879f20)

Have I missed something obvious?

**Comment by aerni** [comment]
It should be `{{ seo:head }}` and not `{{ seo:meta }}`. Was that a typo?

**Comment by ikmolbo** [comment]
Yes, it was a typo (in this Issue) - in my template, I have `{{ seo:head }}`.

**Comment by aerni** [comment]
Add `{{ dump }}` to your layout. Do you see a bunch of seo variables like this?

![CleanShot 2024-10-04 at 12 43 19@2x](https://github.com/user-attachments/assets/990a715f-2249-4e8a-9075-a9fa1e04d9d4)

**Comment by ikmolbo** [comment]
Turns out it was the residue of another tried and uninstalled SEO addon that was interfering with yours. Having manually deleted all that I could find, your package now seems to be working.
