### ISSUE TITLE
/sitemap.xml returns 404

### ISSUE THREAD

**Issue by DevelopmentNightmare** [aerni/statamic-advanced-seo#171]
After installing this package and generating a new sitemap, the URL gives me a 404. I followed all the [documentation](https://advanced-seo.michaelaerni.ch/) and the package is working flawlessly, except for the sitemap. 

The sitemap is enabled inside the advanced-seo config and no-index is **NOT** enabled. And after running the generate command I see the message: "The sitemaps have been succesfully generated". But whenever I go inside the storage folder and open the actual sitemap, this is what it looks like:

`<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" advanced-seo-version="2.9.1">
    </sitemapindex>
`

Any ideas what I could do/check to figure out what's wrong?

**Comment by aerni** [comment]
The sitemaps URL only works on production by default. This is to ensure that nothing gets crawled on other environments. You can change this behavior by adding your environment to the crawling config.

https://github.com/aerni/statamic-advanced-seo/blob/5feb2bbb1457c9021199680764d4e4abb73290f3/config/advanced-seo.php#L201

I should probably add a notice when running the generate command in an unconfigured environment to avoid confusion.

**Comment by JorisOrangeStudio** [comment]
Ran into the same 'issue' so indeed a message will be helpful!

**Comment by aerni** [comment]
Thanks for the feedback. I'll look into it.

**Comment by aerni** [comment]
I've added a note in the latest release. You won't be able to generate sitemaps anymore if the environment is excluded from crawling. I'll also add a note in the docs.
