### ISSUE TITLE
Method Illuminate\Support\Collection::doesntContain does not exist.

### ISSUE THREAD

**Issue by mc4rdle** [aerni/statamic-advanced-seo#18]
Adding any seo tag to the site breaks it with this error, even {{ seo:dump }}

**Details:**
Statamic 3.3.15 Pro
Laravel 8.66.0
PHP 8.0.18
aerni/advanced-seo 1.1.5
aryehraber/statamic-captcha 1.5.2
visuellverstehen/statamic-plausible 1.2.0

**Comment by aerni** [comment]
You should update your Laravel version. The `doesntContain` method was added in [v8.76.2](https://github.com/laravel/framework/releases/tag/v8.76.2). And there was a fix regarding it in [v8.77.0](https://github.com/laravel/framework/releases/tag/v8.77.0). Just update to the latest Laravel 8 version. I will release a fix that will require this version.
