### ISSUE TITLE
Button texts missing

### ISSUE THREAD

**Issue by hgrimelid** [aerni/statamic-advanced-seo#20]
When using locale different from `en` (defined in `app.locale`), only the text key shows in some cases.

See attached examples.

<img width="646" alt="nb" src="https://user-images.githubusercontent.com/40372/173824945-c7b8a01e-298b-4eae-bb78-965ad0cc86a0.png">

<img width="644" alt="en" src="https://user-images.githubusercontent.com/40372/173824937-08bfa472-3b50-4412-9aa8-faf1855cb555.png">

**Comment by aerni** [comment]
This is a Statamic bug as described here https://github.com/statamic/cms/issues/5277 and here https://github.com/statamic/cms/issues/5610.

As a workaround, you can publish the translation files with `php artisan vendor:publish --tag=advanced-seo-translations` and then move the published `fields.php` and `messages.php` into `lang/vendor/advanced-seo/{your_locale}`.
