### ISSUE TITLE
Add ability to retrieve the data for more fields (e.g. "{{ seo:organization_name }}")

### ISSUE THREAD

**Issue by markguleno** [aerni/statamic-advanced-seo#21]
While you can retrieve the data of specific fields such as `{{ seo:title }}`, other fields including `{{ seo:organization_name }}` and `{{ seo:organization_logo }}` aren't available.

Please make all the seo fields configured in the control panel available for use in antlers.

Thank you.

**Comment by aerni** [comment]
I'll have to give this some thought as to how to best approach your request. As of now, Advanced SEO only makes variables available, that are used in its own views. Making all variables available would probably cause some conflicts as fields like the title or OG images are computed fields that take the original field available in the Control Panel and add some more data to it. The title for instance takes the page title and adds the site name.

**Comment by aerni** [comment]
This feature is coming with the next release.
