### ISSUE TITLE
Add a way to hide site name and separator when using Custom Meta Title

### ISSUE THREAD

**Issue by mikemartin** [aerni/statamic-advanced-seo#22]
I like that the Site Name is added when using the custom meta title, but you might want to hide it on the Homepage for instance. Could you add a "Hide Site Title" toggle to disable it in the SEO tab?

<img width="829" alt="Screen Shot 2022-07-08 at 1 07 01 pm" src="https://user-images.githubusercontent.com/414211/177909227-666f46d9-9bbd-47d4-b2fc-789b5c79ab6c.png">

**Comment by aerni** [comment]
I don't quite understand your request. Do I understand correctly that you want to be able to hide the site name (the name that you can set in the general site defaults) from the meta title on the frontend? 

You're saying that the site name is added when using the custom meta title. But the site name is added no matter if you choose auto, default, or custom.

In the image you posted, you added `ShiftCare`. Isn't that the site name? If yes, simply remove it from the meta title to not have it output twice on the frontend.

**Comment by mikemartin** [comment]
For the homepage, it's better to have the site name output first and followed by a tagline:

ShiftCare - Some branded tagline

And then for all other internal pages the site name with be output after the page title.  

Page Title - ShiftCare

But currently it seems like I have to choose one or the other for all pages. In Aardvark and SEO Pro, this was not an issue because the custom title did not append the site name.

**Comment by mikemartin** [comment]
Option 2 sounds great to me. 👍
