### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by Narretz** [aerni/statamic-advanced-seo#23]
It would be great to expose the SEO data via graphql for using statamic as a headless CMS.

So far I cannot see anything being exposed via gql.

It looks like not even the SEO Pro addon by Statamic themselves does this correctly, so there may be an opportunity here to get an edge over the competition. (I have literally no idea how difficult this is)

**Comment by aerni** [comment]
This is on my roadmap. It's quite a big task, though. I'm working on it whenever I get to it.

**Comment by aerni** [comment]
@Narretz I opened a PR to add support for GraphQL. Do you mind giving it a spin? Any feedback is welcomed.

**Comment by Narretz** [comment]
Hi @aerni that's amazing news. I tested the basic functionality and it works and I really like it!

I will test all fields I need and come back with any feedback here

**Comment by Narretz** [comment]
One little thing that may be more a main issue than for this feature is that a few strings are untranslated: 
![Screenshot 2022-08-18 at 18-39-25 Blubber ‹ Pages ‹ Collections ‹ Statamic](https://user-images.githubusercontent.com/1153097/185449636-c01017ad-2496-4fec-a41c-10628146f1b3.png)

**Comment by aerni** [comment]
@Narretz Glad you like it. Please provide feedback here: https://github.com/aerni/statamic-advanced-seo/pull/34

The untranslated strings is an unrelated issue that I've noticed myself.
