### ISSUE TITLE
Href-lang tags not rendered for collection taxonomy routes

### ISSUE THREAD

**Issue by mikemartin** [aerni/statamic-advanced-seo#28]
When a taxonomy route is used for a specific collection (ie: /events/tags/term) the href-lang tags are not rendered.  

Steps to reproduce:
1. Pull down test repo: https://github.com/mikemartin/taxonomy-test
2. Visit the example term at `/events/tag/feast` 
3. See no href-lang tags rendered for that term

**Comment by mikemartin** [comment]
@aerni I've also reported a related issue to Statamic here: https://github.com/statamic/cms/issues/6418

**Comment by aerni** [comment]
This is related to #16. There's currently no way to provide those links.
