### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-advanced-seo#3]
Hey there. I'm excited to see that you are working on an SEO addon. Your other packages have been top notch.

Just wondering:
- Will blade be supported?
- Will the add-on generate reports and SEO recommendations?
  - If so, how will SEO checks performed? I think a lot of SEO plugins make the mistake of analysing back-end content, when they should really be analysing the front-end and what is being shown to the visitor on each public url.
- Will you be including redirects and automatic redirects for multisite environments?

I know that's a lot to ask. I'm just weighing up my options on the various Statamic SEO addons.

Thanks!

**Comment by aerni** [comment]
Thanks for the compliment!

**Will blade be supported?**
Not sure what you want Blade support for?

**Will the add-on generate reports and SEO recommendations?**
Nothing is planned as of now. Sounds like a good but huge feature to implement.

**Will you be including redirects and automatic redirects for multisite environments?**
Not planning to implement this. But might change my mind in the future. I'd suggest you go with the excellent [Redirect addon by Rias](https://statamic.com/addons/rias/redirect).

**Comment by stuartcusackie** [comment]
**Not sure what you want Blade support for?**
Good Question! I was struggling with another Statamic SEO add-on and running into problems related to template inheritance / blade layout components. Nevermind, I think I understand that now.

**Nothing is planned as of now. Sounds like a good but huge feature to implement.**
Yeah, crazy idea. I guess it gets really complicated to do anything except a simple title / description check.

**Not planning to implement this. But might change my mind in the future. I'd suggest you go with the excellent [Redirect addon by Rias](https://statamic.com/addons/rias/redirect).**
Yep, I've just had my first experience with this addon. Seems good so far.

Cheers! Will try this addon soon.

**Comment by aerni** [comment]
Any feedback is welcome. Just DM me on Discord.

**Comment by isaackearl** [comment]
@aerni love the addon, and I'm now using it in 5+ sites... It has become my new default SEO tool.  Making a comment here because the one feature I miss from SEO pro is the report that helps pinpoint basic SEO setup stuff.  I just want to give a +1 to the feature request of generating SEO reports.
