### ISSUE TITLE
Customize which fields are shown in the SEO tab / page

### ISSUE THREAD

**Issue by Narretz** [aerni/statamic-advanced-seo#35]
As a developer / site owner I might not want to expose all the possible fields to site authors. Or maybe the frontend doesn't use Twitter metadata, so I might not want to show these fields to not confuse the authors.

**Comment by aerni** [comment]
The idea behind Advanced SEO was always to make it as customizable as possible. Certain fields like the Sitemap already get removed when the feature is disabled. That being said, I found it quite challenging to make the customization options both very modular while keeping them simple and not too complicated.

From a user's perspective, how would you like to configure the fields to be shown/activated in the SEO tab?

**Comment by Narretz** [comment]
I'm looking at this from two perspectives:

- a client might want certain SEO features (OG Tags) but not be interested in others (sitemap weight), so hiding the latter from the UI streamlines the authoring process
- when you are using statamic headless, your frontend might not support all settings (or the plugin doesn't expose them), so offering them in the UI doesn't make sense either

I think in my case right now it's probably easiest to hide the UI with custom CSS. The other idea is to have specific permission for the different blocks, and let the developer handle acces via roles:

Twitter / OG / Canonical URL / Indexing / Sitemap / JSON LD

If that is possible - since all of these elements are in a single form. Does statamic hide UI elements if the user doesn't have access to them?

**Comment by aerni** [comment]
Making each and every field customizable would be a daunting task. If you want to hide only certain fields like `sitemap_priority` it's probably best to simply hide the field with some custom CSS.

If we're talking about features or UI blocks like Twitter or Sitemap, we have to look at them from two perspectives:

**Enabled/Disabled**
A feature can be disabled in the config, which removes all associated fields from the blueprint and doesn't expose them to the frontend in any way.

**Visible/Hidden**
A feature is generally enabled, and the fields are exposed to the frontend. But only people with permission can see and edit them in the UI. I'm not sure if this can be done, as Statamic doesn't have a concept of field-specific permissions. I'd have to look into this.

Does this make sense?

**Comment by aerni** [comment]
Following up on this. Statamic doesn't have the concept of field-level permissions. There is an open feature idea for it: https://github.com/statamic/ideas/issues/399

I'm exploring the ability to customize the SEO fields. This would allow you to remove, rearrange, or add your own SEO fields to your blueprints.

**Comment by aerni** [comment]
This feature will be released in Advanced SEO v2. You'll be able to customize the fieldset that is displayed in the SEO tab. You can also go completely wild and customize the fields for each blueprint.
