### ISSUE TITLE
Allow custom @auto for other fields

### ISSUE THREAD

**Issue by Narretz** [aerni/statamic-advanced-seo#36]
"Meta title" by default uses `@auto` to inherit the value from the `title` field, because every entry in statamic has a title field. It would be cool if you could use `@auto` for example for "meta description" and then select a field in the collection / taxonomy type from which to inherit.

**Comment by aerni** [comment]
I intentionally didn't add this feature for multiple reasons. 

From a technical point of view, it would add a lot of complexity, while only a handful of fields, e.g. the `seo_description`, would benefit from it. And if the feature existed, you could only ever inherit from fields that are of the same type. In the case of the `seo_description` field, you could only inherit from fields of `type: textarea`. So I don't really see the point if you could just enter the content in the `seo_description` field to start with.

From a content point of view, I want to encourage good SEO habits. SEO fields are special and should be treated as such. It doesn't make sense to inherit from a textarea with a lot of content when the meta description will be cut down to about 160 characters in real life anyways. The meta description should be tailored for SEO and not a simple copy from another field.

All that being said, if you have a specific use case for this, feel free to change my mind.

**Comment by Narretz** [comment]
Hey @aerni this makes sense. I've looked at this from a perspective of a dev who doesn't really know much about SEO. If it's really just description and nothing else, then it doesn't make sense to implement it.
