### ISSUE TITLE
Variables for JSON-LD Schema

### ISSUE THREAD

**Issue by insight-media** [aerni/statamic-advanced-seo#39]
I'd like to define a JSON-LD Schema on a collection. So every entry will have it's own specific rich snippet data.

Is there a way to use variables in the json data, so a specific JSON-LD schema will be generated per entry ?

For example:

`{
   "@context":"https://schema.org/",
   "@type":"Product",
   "name":"{{ name }}",
   "image":"{{ image }}",
   "description":"{{ description }}",
   "brand":{
      "@type":"Brand",
      "name":"{{ brand }}"
   }
}`

`{
   "@context":"https://schema.org/",
   "@type":"Product",
   "name":"Name of product",
   "image":"https://mywebsite.com/image.jpg",
   "description":"Product description",
   "brand":{
      "@type":"Brand",
      "name":"Name of brand"
   }
}`

**Comment by JoeriE** [comment]
This one would be a great addition!

**Comment by aerni** [comment]
Support for variables was just added in #52. It will be released with Advanced SEO v2 #45.
