### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by janh-kramer** [aerni/statamic-advanced-seo#40]
Hallo, 
I just updated statamic from v3.3.43 => v3.3.49 and now I get following error: 
`Declaration of 
Aerni\AdvancedSeo\Data\SeoDefaultSet::in(string $locale): ?Aerni\AdvancedSeo\Data\SeoVariables must be compatible with Statamic\Contracts\Globals\GlobalSet::in($locale) `
in
`vendor / aerni / advanced-seo / src / Data / SeoDefaultSet.php: 141`

Do you have any suggestion how I can fix this?
Thanks Jan

**Comment by janh-kramer** [comment]
As a quickfix I downgraded statamic to v3.3.43 and now it's working again. What do I need to do to update?

**Comment by aerni** [comment]
This error is probably related to this PR: https://github.com/statamic/cms/pull/6938. I will take a look and release a patch when I find some time.

**Comment by janh-kramer** [comment]
Thanks for the quick fix, it's working again!
