### ISSUE TITLE
Invalid route action

### ISSUE THREAD

**Issue by Krzemo** [aerni/statamic-advanced-seo#51]
```
UnexpectedValueException
Invalid route action: [Aerni\AdvancedSeo\Http\Controllers\Aerni\AdvancedSeo\Http\Controllers\Cp\ConditionsController]
```
at
```
Illuminate\Routing\RouteAction::makeInvokable
vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
```
caused by
```
    protected static function makeInvokable($action)
    {
        if (! method_exists($action, '__invoke')) {
            throw new UnexpectedValueException("Invalid route action: [{$action}].");
        }
 
        return $action.'@__invoke';
    }

```

Statamic 3.4.4
PHP 8.2
Laravel 8.83.27

**Comment by aerni** [comment]
Latest version of the addon?

**Comment by aerni** [comment]
And please provide some more info on how to reproduce this.

**Comment by Krzemo** [comment]
This is prolly an edgecase and im not sure if its worth bothering.
I have an old site that I just upgraded from 3.2 to 3.4 and installed Adv SEO addon.
I think the reason for the error is that old site is still running on L8.
To replicate it I would have to go trough Laravel downgrade process for new Statamic install and see if error is still there. (or I can give you an access to site repo ...)

Maybe I will just try to upgrade to L9 and save us time ;)

**Comment by aerni** [comment]
Just upgrade to L9. I'll drop support for L8 very soon.
