### ISSUE TITLE
Multi-site error

### ISSUE THREAD

**Issue by Narretz** [aerni/statamic-advanced-seo#60]
This is a follow-up to #56 

The error persists, and I'm pretty sure it's a problem with advanced-seo, not the multisite feature. Even after converting a clean statamic 3 install to multisite, I get the error seen here: https://flareapp.io/share/omwrgWR5#F109

From what I can tell, the problem is in `Aerni \ AdvancedSeo \ Data \ SeoDefaultSet :blueprint` function.
https://github.com/aerni/statamic-advanced-seo/blob/2c635c13fdc74f7a35d3ac82dda90bc2629b88e3/src/Data/SeoDefaultSet.php#L204

When you go to "cp/advanced-seo/site/general", and you don't have multisite configured, "{$this->type}::{$this->handle}" will be "site::general", but when you multisite configured, "{$this->type}::{$this->handle}" will be for example "site/default::general", for which no blueprint exists, and the error is thrown. The same is true for collections settings etc.

What's noteworthy is that this only happens the second time after you go to  "cp/advanced-seo/site/general", because advanced-seo will create the localizations initially.

**Comment by Narretz** [comment]
Hi @aerni,

here's a video with the error.

https://github.com/aerni/statamic-advanced-seo/assets/1153097/e1d7f477-d634-4738-bacc-cac7be53a180

It happens after doing these steps:

- install statamic (with statamic new)
- run `php artisan  key:generate`
- create multi site (with php please multi) create one site with handle "en"
- composer require aerni/advanced-seo


Steps to repro

- go to "SEO -> site -> general"
- add "site name"
- save
- go to "Utilities" -> "Cache Manager" -> "Content Stache" -> "Clear All"
- in the sidebar, you will see "Duplicate IDs". This is probably a symptom of the problem
- go to "SEO -> site -> general"

-> error appears





- the error does not go away after clearing all caches
- it only goes away if you delete the contents of the content/seo folder completely


I'm running out of ideas tbh. Maybe it's a Windows thing?

**Comment by Narretz** [comment]
Hi @aerni thanks for looking into this (again)!

The repo is here: https://github.com/Narretz/advanced-seo-multi

I didn't commit the vendor / node_modules files, so you need to install them before you make the tests.

**Comment by aerni** [comment]
I just gave your sample repo a try and followed the instructions you provided above. Still no luck in reproducing the issue. It must be an environment thing or some other strange issue. Do you run into this on local only? Have you tried on a staging or production server?

**Comment by Narretz** [comment]
It shouldn't come as a surprise (but it did) that this was a Windows / Unix path error. See #80 for a fix
