### ISSUE TITLE
Localization doesn't show

### ISSUE THREAD

**Issue by mynetx** [aerni/statamic-advanced-seo#62]
On the SEO tab of the Pages collection, the strings do not show up correctly. Instead, a placeholder is shown for some of them. Why?

<img width="1138" alt="image" src="https://github.com/aerni/statamic-advanced-seo/assets/6348321/c68e8a51-ffe0-46dc-8875-6a24aacb08b9">

**Environment**
Laravel Version: 9.52.7
PHP Version: 8.2.4
Composer Version: 2.4.3
Environment: local

**Statamic**
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.11 PRO

**Statamic Addons**
aerni/advanced-seo: 2.0.6

**Comment by aerni** [comment]
This is a Statamic bug. See [this issue](https://github.com/aerni/statamic-advanced-seo/issues/20) for a workaround.
