### ISSUE TITLE
Assets are not Augmented when returned by Statamics Rest API

### ISSUE THREAD

**Issue by goellner** [aerni/statamic-advanced-seo#82]
the assets are not augmented, when returned by statamics rest api. 

I have a custom AssetResource set up and it would be good if the addon would return the same augmented values for assets as the rest of the api. https://statamic.dev/rest-api#customizing-resources

**Comment by aerni** [comment]
Please provide more information about what you're trying to do and how I can replicate the issue. Generally speaking, this addon doesn't officially support the REST API.
