### ISSUE TITLE
Weird button labels

### ISSUE THREAD

**Issue by semvgelooven** [aerni/statamic-advanced-seo#92]
When going to my Collection in Statamic I see weird button labels. Is this a translation issue?

![Screenshot 2023-08-02 at 12 42 39](https://github.com/aerni/statamic-advanced-seo/assets/4249218/e00cf4cb-cf86-4d2b-9062-8ec7306936e0)

**Comment by aerni** [comment]
This is a Statamic bug. See https://github.com/aerni/statamic-advanced-seo/issues/20 for a workaround.
